name: .NET
#
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: Sources

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.100-preview.7.22377.5
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer
    - name: Remove docker
      run: docker rm demo-docker
    - name: Run
      run: docker run -it --rm --detach --name demo-docker -p 5010:80 my-awesome-container-app:1.0.0
